In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Question 1

In [45]:
# What's the version of Pandas that you installed?
print(f'The pandas version is {pd.__version__}')

The pandas version is 1.4.2


In [46]:
# Import the dataset
df =  pd.read_csv('laptops.csv')

In [47]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

## Question 2

In [48]:
# Q2: Records count
# The shape attribute returns a tuple where the first element is the number of rows.
print(f'There are {df.shape[0]} laptop brands presented in this dataset')

There are 2160 laptop brands presented in this dataset


## Question 3

In [49]:
brand_names = list(df['Brand'].unique())

In [50]:
laptop_brands = df['Brand'].nunique()
print(f'There are {laptop_brands} in the dataset and they are: {brand_names}')

There are 27 in the dataset and they are: ['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple', 'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft', 'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver', 'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme', 'Toshiba']


## Question 4

In [51]:
# Q4: Columns with missing values count
# Use isna() to find missing values, sum() to get column-wise count, and gt(0).sum() to count columns with missing values.
missing_values_count = df.isnull().sum().gt(0).sum()
missing_values_count

3

In [52]:
sum = 0
columns = []
for col in df.columns:
    if df[col].isnull().sum() > 0:
        sum+=1
        columns.append(col)
        
print(f'There are {missing_values_count} columns with missing values and they are: {columns[0]}, {columns[1]} and {columns[2]}')        

There are 3 columns with missing values and they are: Storage type, GPU and Screen


## Question 5

In [53]:
# Q5: Maximum final price of Dell notebooks
# Filter rows where 'Brand' is 'Dell' and get the maximum value of 'Final Price' column.
max_price = df[df['Brand'].str.lower() == 'dell']['Final Price'].max()
print(f'The maximum final price of Dell notebooks in the dataset is {max_price}')

The maximum final price of Dell notebooks in the dataset is 3936.0


## Question 6

In [54]:
# Q6: Median value of Screen column before and after filling missing values
# Calculate the median value of 'Screen' column before filling missing values.
median_prior = df['Screen'].median()
print(f'The median of the Screen column before imputation is {median_prior}')

The median of the Screen column before imputation is 15.6


In [55]:
# Calculate the most frequent value (mode) of the 'Screen' column.
mode = df['Screen'].mode()[0]
print(f'The most frequent value of the Screen column is {mode}')

The most frequent value of the Screen column is 15.6


In [56]:
# Use fillna() to fill missing values in 'Screen' column with the most frequent value.
df['Screen'].fillna(value=mode, inplace=True)

In [57]:
# Calculate the median value of 'Screen' column after filling missing values.
median_after = df['Screen'].median()
print(f'The median of the Screen column after imputation is {median_after}')
median_screen_changed = median_prior != median_after
print(f"Has the median value of 'Screen' changed after filling missing values? {median_screen_changed}")

The median of the Screen column after imputation is 15.6
Has the median value of 'Screen' changed after filling missing values? False


## Question 7

In [58]:
# Q7: Sum of weights (Linear Regression Implementation)
# Select all the "Innjoo" laptops from the dataset and only columns RAM, Storage, Screen
selected_columns = df[df['Brand'].str.lower() == 'innjoo'][['RAM', 'Storage', 'Screen']]
selected_columns

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [59]:
# Get the underlying NumPy array (X)
X = selected_columns.values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [60]:
# Compute matrix-matrix multiplication between the transpose of X and X (XTX)
XTX = X.T@(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [61]:
# Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [62]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100]
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [63]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100]
w = XTX_inv@X.T@y
w

array([45.58076606,  0.42783519, 45.29127938])

In [64]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100]
sum_w = w.sum()
sum_w

91.2998806299555

In [65]:
print(f'The sum of all the elements is {round(sum_w,2)}')

The sum of all the elements is 91.3
