In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('car_fuel_efficiency.csv')
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369


In [11]:
pandas_version = pd.__version__
print(f'The pandas version is {pandas_version}')

The pandas version is 2.2.3


In [10]:
Records_count = df.shape[0]
print(f'The records count is {Records_count}')

The records count is 9704


In [14]:
fuel_types = df['fuel_type'].nunique()
print(f'There are {fuel_types} fuel types in the data')

There are 2 fuel types in the data


In [25]:
missing_values = 0
for col in df.columns:
    if df[col].isnull().sum() != 0:
        missing_values+=1
    else:
        continue
print(f'The number of columns with missing values is {missing_values}')

The number of columns with missing values is 4


In [37]:
max_fuel_efficiency = df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max().round(3)
print(f'The maximum fuel efficiency is {max_fuel_efficiency}')

The maximum fuel efficiency is 23.759


In [33]:
median_original = df['horsepower'].median()
print(f"Original median horsepower: {median_original}")
mode_value = df['horsepower'].mode()[0]
print(f"Most frequent horsepower value (mode): {mode_value}")
df_filled = df.copy()
df_filled['horsepower'] = df_filled['horsepower'].fillna(mode_value)
print(f"Missing values after filling: {df_filled['horsepower'].isna().sum()}")
median_after_fill = df_filled['horsepower'].median()
print(f"Median horsepower after filling: {median_after_fill}")
# Compare the medians
print("\n" + "="*50)
print("COMPARISON:")
print(f"Original median: {median_original}")
print(f"After filling median: {median_after_fill}")
print(f"Difference: {median_after_fill - median_original}")

if median_after_fill > median_original:
    print("\nAnswer: Yes, it increased")
elif median_after_fill < median_original:
    print("\nAnswer: Yes, it decreased")
else:
    print("\nAnswer: No, it stayed the same")

Original median horsepower: 149.0
Most frequent horsepower value (mode): 152.0
Missing values after filling: 0
Median horsepower after filling: 152.0

COMPARISON:
Original median: 149.0
After filling median: 152.0
Difference: 3.0

Answer: Yes, it increased


In [35]:
asian_cars = df[df['origin'] == 'Asia']
print(f"Total Asian cars: {len(asian_cars)}")

# Step 2: Select only columns vehicle_weight and model_year
# Step 3: Select the first 7 values
selected_data = asian_cars[['vehicle_weight', 'model_year']].head(7)
print("\nFirst 7 Asian cars:")
print(selected_data)
X = selected_data.values
print(f"\nX shape: {X.shape}")
print("X matrix:")
print(X)
XTX = X.T @ X
print("\nXTX (X^T * X):")
print(XTX)
XTX_inv = np.linalg.inv(XTX)
print("\nInverse of XTX:")
print(XTX_inv)
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print("\ny:")
print(y)
w = XTX_inv @ X.T @ y
print("\nw (result):")
print(w)
result_sum = w.sum()
print(f"\nSum of all elements in w: {result_sum}")

Total Asian cars: 3247

First 7 Asian cars:
    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

X shape: (7, 2)
X matrix:
[[2714.21930965 2016.        ]
 [2783.86897424 2010.        ]
 [3582.68736772 2007.        ]
 [2231.8081416  2011.        ]
 [2659.43145076 2016.        ]
 [2844.22753389 2014.        ]
 [3761.99403819 2019.        ]]

XTX (X^T * X):
[[62248334.33150762 41431216.50732678]
 [41431216.50732678 28373339.        ]]

Inverse of XTX:
[[ 5.71497081e-07 -8.34509443e-07]
 [-8.34509443e-07  1.25380877e-06]]

y:
[1100 1300  800  900 1000 1100 1200]

w (result):
[0.01386421 0.5049067 ]

Sum of all elements in w: 0.5187709081074001
